# Database
MYSQL_USERNAME: root
MYSQL_PASSWORD:
MYSQL_HOST: localhost
MYSQL_PORT: 3306
MYSQL_DB: spcloud

# Server
SERVER_PORT: 9000
ACTIVE_PROFILE: dev

# Email Config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: hamzajaa2017@gmail.com
EMAIL_PASSWORD: dxdlxflaluwksasb
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}




